version: '3'
services:
  terraform-gcp-service:
    container_name: terraform-gcp-container
    image: terraform-gcp-image
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/terraform:/terraform
      - ${PWD}/.credentials:/credentials  # terraform コンテナの credentials を同期
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      GOOGLE_APPLICATION_CREDENTIALS: /credentials/application_default_credentials.json   # terraform コンテナの credentials の json ファイルを設定
#    env_file:
#      - gcp_key.env
