---
# Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-pod
  labels:
    app: fast-api-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-api-pod
  template:
    metadata:
      labels:
        app: fast-api-pod
    spec:
      containers:
      - name: fast-api-container
        image: gcr.io/my-project2-303004/fast-api-image-gke:latest
        ports:
        - containerPort: 5000
          name: http-server
        env:
          - name: DEBUG
            value: "True"
        command: ["/bin/sh","-c"]
        args: ["gunicorn app:app --bind 0.0.0.0:5000 -k uvicorn.workers.UvicornWorker --workers 1 --threads 1 --backlog 512 --timeout 1000000 --reload"]
#        resources:
#          requests:
#            cpu: 100m
#            memory: "0.1Gi"
#      nodeSelector:
#        cloud.google.com/gke-spot: "true"     # Spot インスタンスで Pod を構成
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: fast-api-server
spec:
  type: LoadBalancer   # L4 ロードバランサーは使用しない。代わりに L7 ロードバランサーである Ingress を使用する
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: fast-api-pod
